apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test1
  description: description of test
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: Signzy-API
