apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test12345
  description: description of test
  tags:
    - go
    - website
  links: 
    - url: https://github.com/SamarthNanda1114
      title: My github
spec:
  type: service
  lifecycle: production
  owner: Signzy-API
