apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Signzy Test API
  description: This is a test API for backstage
  tags:
    - Signzy 
    - API Team
  links: 
    - url: https://github.com/SamarthNanda1114
      title: My github
    - url: https://signzy.com
      title: Signzy
    - url: https://bitbucket.org/dashboard/overview
      title: Bitbucket
spec:
  type: service
  lifecycle: production
  owner: Signzy-API
